// Placeholder for JavaScript logic
// This script will handle:
// 1. Fetching data (initially from a JSON file generated by a script)
// 2. Populating categories and items in the sidebar
// 3. Handling search functionality
// 4. Displaying comparison images when an item is selected
// 5. Toggling category visibility

document.addEventListener('DOMContentLoaded', () => {
    const categoriesContainer = document.getElementById('categories');
    const comparisonArea = document.getElementById('comparison-area');
    const searchInput = document.getElementById('search-input');
    const noItemSelectedMessage = document.getElementById('no-item-selected');
    const themeToggle = document.getElementById('theme-toggle');
    const lightIcon = document.getElementById('light-icon');
    const darkIcon = document.getElementById('dark-icon');
    const themeText = document.getElementById('theme-text');
    let allItems = []; // To store all items for searching
    let currentData = null; // Store the fetched data

    // Theme toggle functionality
    function initTheme() {
        // Check for saved theme preference or use system preference
        const savedTheme = localStorage.getItem('theme');
        if (savedTheme === 'dark') {
            enableDarkMode();
        } else if (savedTheme === 'light') {
            enableLightMode();
        } else {
            // Use system preference if no saved preference
            if (window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) {
                enableDarkMode();
            }
        }
    }

    function enableDarkMode() {
        document.body.classList.add('dark-theme');
        lightIcon.style.display = 'none';
        darkIcon.style.display = 'block';
        themeText.textContent = 'Chế độ sáng';
        localStorage.setItem('theme', 'dark');
    }

    function enableLightMode() {
        document.body.classList.remove('dark-theme');
        lightIcon.style.display = 'block';
        darkIcon.style.display = 'none';
        themeText.textContent = 'Chế độ tối';
        localStorage.setItem('theme', 'light');
    }

    themeToggle.addEventListener('click', () => {
        if (document.body.classList.contains('dark-theme')) {
            enableLightMode();
        } else {
            enableDarkMode();
        }
    });

    // Initialize theme
    initTheme();

    // Function to fetch data and initialize the page
    async function fetchData() {
        try {
            // Use import.meta.env.BASE_URL to get the configured base path from Vite
            // Or use a relative path that works regardless of base path configuration
            const response = await fetch('./data.json');
            if (!response.ok) {
                console.error(`Failed to fetch data.json. Status: ${response.status}, StatusText: ${response.statusText}`);
                const responseText = await response.text();
                console.error("Response body (if available):", responseText);
                throw new Error(`HTTP error! status: ${response.status}`);
            }
            currentData = await response.json();
            // Use the new function to populate the tree
            populateTreeSidebar(currentData.categories);
            collectAllItems(currentData.categories);
        } catch (error) {
            console.error("Could not fetch data:", error);
            categoriesContainer.innerHTML = `<p style="color: red;">Lỗi tải dữ liệu (data.json). Hãy đảm bảo bạn đã chạy 'npm run scan' thành công và kiểm tra Console (F12) trong trình duyệt để biết thêm chi tiết.</p>`;
        }
    }

    // --- NEW Function to populate the sidebar as a tree ---
    function populateTreeSidebar(categoriesData) {
        categoriesContainer.innerHTML = ''; // Clear previous content
        const treeRoot = document.createElement('ul');
        treeRoot.classList.add('category-tree');

        for (const categoryName in categoriesData) {
            const items = categoriesData[categoryName];
            if (items.length > 0) {
                // Create category node
                const categoryNode = document.createElement('li');
                categoryNode.classList.add('category-node');

                const categoryTitle = document.createElement('span');
                categoryTitle.textContent = categoryName;
                categoryTitle.classList.add('category-title');
                categoryNode.appendChild(categoryTitle);

                // Create list for items within the category
                const itemList = document.createElement('ul');
                itemList.classList.add('item-list'); // Initially hidden by CSS

                items.forEach(item => {
                    const itemNode = document.createElement('li');
                    itemNode.classList.add('item-node');
                    itemNode.textContent = `${item.id ? item.id + ' - ' : ''}${item.name}`; // Display ID and name
                    itemNode.dataset.category = categoryName;
                    itemNode.dataset.itemId = item.id || item.name.replace(/ /g, '_'); // Use ID or name as identifier
                    itemNode.addEventListener('click', (e) => {
                        e.stopPropagation(); // Prevent category toggle when item is clicked
                        displayComparison(item);
                    });
                    itemList.appendChild(itemNode);
                });

                categoryNode.appendChild(itemList);

                // Add click listener to category title to toggle item list
                categoryTitle.addEventListener('click', () => {
                    categoryNode.classList.toggle('expanded');
                });

                treeRoot.appendChild(categoryNode);
            }
        }
        categoriesContainer.appendChild(treeRoot);
    }

    // Function to collect all items for search functionality
    function collectAllItems(categoriesData) {
        allItems = [];
        for (const categoryName in categoriesData) {
            categoriesData[categoryName].forEach(item => {
                allItems.push(item);
            });
        }
    }

    // Function to display comparison images
    function displayComparison(item) {
        comparisonArea.innerHTML = ''; // Clear previous comparison
         if (noItemSelectedMessage) noItemSelectedMessage.style.display = 'none'; // Hide initial message

        // Create containers for each version
        const awakenContainer = createImageContainer('MU Awaken', item.images.awaken);
        const originContainer = createImageContainer('MU Origin', item.images.origin);

        comparisonArea.appendChild(awakenContainer);
        comparisonArea.appendChild(originContainer);

        // Highlight selected item in sidebar
        highlightSelectedItem(item.category, item.id || item.name.replace(/ /g, '_'));
    }

    // Helper function to create image container for a version
    function createImageContainer(versionName, images) {
        const container = document.createElement('div');
        container.classList.add('image-container');

        const title = document.createElement('h4');
        title.textContent = versionName;
        container.appendChild(title);

        if (images.length > 0) {
            images.forEach(imgPath => {
                // Create a fixed-size container for the image
                const previewContainer = document.createElement('div');
                previewContainer.classList.add('image-preview-container');
                container.appendChild(previewContainer);
                
                // Create and add the image to the container
                const img = document.createElement('img');
                img.src = `./${imgPath}`;
                img.alt = `${versionName} image`;
                previewContainer.appendChild(img);
            });
        } else {
            const noImageText = document.createElement('p');
            noImageText.textContent = 'Không có hình ảnh.';
            container.appendChild(noImageText);
        }

        return container;
    }

    // Function to highlight the selected item in the sidebar
    function highlightSelectedItem(category, itemId) {
        const previouslySelected = categoriesContainer.querySelector('.selected-item');
        if (previouslySelected) {
            previouslySelected.classList.remove('selected-item');
        }
        // Update selector for the tree structure
        const currentItemElement = categoriesContainer.querySelector(`.item-node[data-category="${category}"][data-item-id="${itemId}"]`);
        if (currentItemElement) {
            currentItemElement.classList.add('selected-item');
            // Optionally expand the parent category if it's not already
            const parentCategory = currentItemElement.closest('.category-node');
            if (parentCategory && !parentCategory.classList.contains('expanded')) {
                parentCategory.classList.add('expanded');
            }
        }
    }

    // Function to handle search input (Updated for Tree View)
    function handleSearch() {
        const searchTerm = searchInput.value.toLowerCase().trim();
        const allCategoryNodes = categoriesContainer.querySelectorAll('.category-node');
        const allItemNodes = categoriesContainer.querySelectorAll('.item-node');

        if (searchTerm === '') {
            // Reset view: hide all items, collapse categories, show all categories
            allItemNodes.forEach(node => node.style.display = 'list-item'); // Show all items initially
            allCategoryNodes.forEach(node => {
                node.style.display = 'list-item'; // Ensure category node itself is visible
                node.classList.remove('expanded'); // Collapse category
            });
            return;
        }

        let hasResults = false;
        allCategoryNodes.forEach(categoryNode => {
            const itemList = categoryNode.querySelector('.item-list');
            const items = itemList.querySelectorAll('.item-node');
            let categoryHasMatch = false;

            items.forEach(itemNode => {
                const itemName = itemNode.textContent.toLowerCase();
                const itemId = itemNode.dataset.itemId.toLowerCase();
                const isMatch = itemName.includes(searchTerm) || itemId.includes(searchTerm);

                itemNode.style.display = isMatch ? 'list-item' : 'none';
                if (isMatch) {
                    categoryHasMatch = true;
                    hasResults = true;
                }
            });

            // Show/hide category based on whether it contains matching items
            categoryNode.style.display = categoryHasMatch ? 'list-item' : 'none';
            // Expand category if it has matches
            if (categoryHasMatch) {
                categoryNode.classList.add('expanded');
            } else {
                categoryNode.classList.remove('expanded');
            }
        });
        // Optionally: Add a message if no results found
        // if (!hasResults) { ... }
    }

    // Add event listener for search input
    searchInput.addEventListener('input', handleSearch);

    // Initial data fetch
    fetchData();
}); 